# コンテナイメージ名
IMAGE_NAME = necbaas/node-logic-server:8

# コンテナ名
CONTAINER_NAME = node-logic-server-8-001

# ロジックサーバのコードの格納先（ホスト側のパス）
LOGIC_SERVER_HOST_DIR = ~/work/work_docker/nodejs_http

include ../common/Makefile.common
