# コンテナイメージ名
IMAGE_NAME = necbaas/java-logic-server:11

# コンテナ名
CONTAINER_NAME = java-logic-server-11-001

# ロジックサーバのコードの格納先（ホスト側のパス）
LOGIC_SERVER_HOST_DIR = ~/work/work_docker/java_http

include ../common/Makefile.common
